# Generated by Django 5.1 on 2024-09-19 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(default='', null=True, unique=True)),
                ('date', models.DateField()),
                ('img', models.CharField(max_length=50, null=True)),
                ('excerpt', models.CharField(default='', max_length=300, null=True)),
                ('content', models.TextField(verbose_name=1000)),
                ('author', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='blog.author')),
            ],
        ),
    ]
